# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\borre\PycharmProjects\TPL_APP\gui\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1385, 791)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sup_container = QtWidgets.QHBoxLayout()
        self.sup_container.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.sup_container.setSpacing(15)
        self.sup_container.setObjectName("sup_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_title.setFont(font)
        self.lb_title.setTextFormat(QtCore.Qt.RichText)
        self.lb_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lb_title.setObjectName("lb_title")
        self.verticalLayout_4.addWidget(self.lb_title)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_load_files = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btn_load_files.setFont(font)
        self.btn_load_files.setObjectName("btn_load_files")
        self.verticalLayout_6.addWidget(self.btn_load_files)
        self.btn_proccess_files = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.btn_proccess_files.setFont(font)
        self.btn_proccess_files.setObjectName("btn_proccess_files")
        self.verticalLayout_6.addWidget(self.btn_proccess_files)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_5.addWidget(self.dateEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.sup_container.addLayout(self.verticalLayout_4)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logo.setWordWrap(True)
        self.logo.setObjectName("logo")
        self.sup_container.addWidget(self.logo)
        self.sup_container.setStretch(0, 2)
        self.sup_container.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.sup_container, 0, 0, 1, 1)
        self.tb_files = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tb_files.setFont(font)
        self.tb_files.setAcceptDrops(True)
        self.tb_files.setAutoFillBackground(True)
        self.tb_files.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tb_files.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tb_files.setMidLineWidth(1)
        self.tb_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tb_files.setAlternatingRowColors(True)
        self.tb_files.setObjectName("tb_files")
        self.tb_files.setColumnCount(0)
        self.tb_files.setRowCount(0)
        self.gridLayout_2.addWidget(self.tb_files, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1385, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about_software = QtWidgets.QAction(MainWindow)
        self.about_software.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.about_software.setFont(font)
        self.about_software.setObjectName("about_software")
        self.actionAbrir_INPUT = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionAbrir_INPUT.setFont(font)
        self.actionAbrir_INPUT.setObjectName("actionAbrir_INPUT")
        self.actionAbrir_OUTPUT = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionAbrir_OUTPUT.setFont(font)
        self.actionAbrir_OUTPUT.setObjectName("actionAbrir_OUTPUT")
        self.actionLimpiar_INPUT = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionLimpiar_INPUT.setFont(font)
        self.actionLimpiar_INPUT.setObjectName("actionLimpiar_INPUT")
        self.actionLimpiar_OUTPUT = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionLimpiar_OUTPUT.setFont(font)
        self.actionLimpiar_OUTPUT.setObjectName("actionLimpiar_OUTPUT")
        self.menuAbout.addAction(self.actionAbrir_INPUT)
        self.menuAbout.addAction(self.actionAbrir_OUTPUT)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionLimpiar_INPUT)
        self.menuAbout.addAction(self.actionLimpiar_OUTPUT)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.about_software)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplicación TPL"))
        self.lb_title.setText(_translate("MainWindow", "GENERADOR ARCHIVOS TPL"))
        self.btn_load_files.setText(_translate("MainWindow", "Cargar archivos"))
        self.btn_proccess_files.setText(_translate("MainWindow", "Procesar archivos"))
        self.label.setText(_translate("MainWindow", "(mm/dd/yyyy):"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/logo/logo.jpg\"/></p></body></html>"))
        self.tb_files.setSortingEnabled(True)
        self.menuAbout.setTitle(_translate("MainWindow", "Menú"))
        self.about_software.setText(_translate("MainWindow", "Acerca del software"))
        self.actionAbrir_INPUT.setText(_translate("MainWindow", "Abrir INPUT"))
        self.actionAbrir_OUTPUT.setText(_translate("MainWindow", "Abrir OUTPUT"))
        self.actionLimpiar_INPUT.setText(_translate("MainWindow", "Limpiar INPUT"))
        self.actionLimpiar_OUTPUT.setText(_translate("MainWindow", "Limpiar OUTPUT"))
import resources_rc
